# SPDX-FileCopyrightText: 2026 Lord-Valen
#
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  reuse_compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v6
  pnpm_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
